Popup detail for mobile and desktop feature
zewdu444/personal_portfolio pull request #11
Opened 2022-12-21 20:02 UTC by zewdu444

# Popup detail for mobile and desktop feature

- Refactored all works card using JavaScript
- Fix linter error on JavaScript and CSS
- Popup windows  detail implemented

2022-12-21 20:41 UTC, huseyinbiyik commented
Hi @zewdu444,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that has some missing sections on Readme file. Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the sections exist in yours and placeholders are replaced with your project and personal data. Only optional section is FAQ.  Also please make sure you deleted the logo on the top unless you have your own personal logo. This is crucial to have a professional and instructive repository. 👌

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-22 09:10 UTC, tufoinnkuo10 requested changes
Hi @zewdu444 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Git flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-22 09:10 UTC, tufoinnkuo10 commented on index.html
> +      <section class="popup" id="popupmenu">
- [ ] nice work. please kindly align the link button and tech buttons with the image. the top left text is aligned with the image as well. this enables but it to look more like the original design
yours
![Screenshot (690)_LI](https://user-images.githubusercontent.com/65298048/209090789-6b8d86a4-12dd-4106-b76f-7ac418f9092f.jpg)
figma
![Screenshot (691)](https://user-images.githubusercontent.com/65298048/209091058-46a298af-2e86-466d-82a9-456fa878f0c0.png)

2022-12-22 09:10 UTC, tufoinnkuo10 commented on index.html
> +                  See Source <i class="fa-brands fa-github"></i>
- [x] nice work. Please, the popup `description,` the `seelive` and `seesource` buttons, should come from their different respective project arrays. This is because the different projects will have different links and different descriptions concerning that particular project. Please fix that.

2022-12-22 09:10 UTC, tufoinnkuo10 commented on js/script.js
> +    mobileName: 'Tonic',
- [ ] please do not separate the mobile popup from the desktop.  Iterate the array only once and style the popup, so it suits both versions using media queries in CSS, so it can be responsive

2022-12-22 10:34 UTC, zewdu444 commented on index.html
> +                  See Source <i class="fa-brands fa-github"></i>
@tufoinnkuo10 thanks  I fixed based on you feedback.

2022-12-22 10:35 UTC, zewdu444 commented on index.html
> +      <section class="popup" id="popupmenu">
@tufoinnkuo10 thanks I fixed based on you feedback.

2022-12-22 10:38 UTC, zewdu444 commented on js/script.js
> +    mobileName: 'Tonic',
@huseyinbiyik Thank you for the input. I divided them because of where they were on the Figma design card; when switching between desktop and mobile, the data is different.

2022-12-22 11:08 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @zewdu444 ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- [x] Linters are passing :+1: 
- [x] Good use of GitHub flow :+1: 
- [x] Good PR message :clap: 
## Optional suggestions :small_airplane: 
- [OPTIONAL] I think it would be better to write more descriptive commit messages, describing the changes you have added clearly.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 11:08 UTC, GedeonTS commented on css/style.css
> +  }
- [ OPTIONAL ] In my opinion it would be good to keep the height of this section to auto and allow it overflow-y to scroll allowing the user to scroll and see the entire pop-up.
YOUR DESIGN:

![Screenshot from 2022-12-22 12-51-43](https://user-images.githubusercontent.com/97834160/209120736-255356e0-c164-45c6-ba44-acdfdefbd289.png)

2022-12-22 11:35 UTC, merged