Desktop  feature responsive web design
zewdu444/personal_portfolio pull request #4
Opened 2022-12-08 20:22 UTC by zewdu444

#Desktop feature responsive web design for portfolio page

- Linter ,GitHub flow and gitignore file has been configured.
- Medeia queries has been used for mobile and desktop feature.
- For html elements set  a character of visibilities depending on screen size.

2022-12-08 21:23 UTC, Ugboaja-Uchechi requested changes
Hi @zewdu444, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +  .container {
- [x] Great job using media queries 👍. Although, there should only be one media query with a `min-width: 768px`. Kindly  use just one media query for this and add all the necessary code to make your design responsive to it 🙏

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [x] When on a smaller desktop screen your text spills out from it's container. Kindly make your design responsive on all desktop screens 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206564738-64085618-00bf-4e4f-98e9-93e663902cb2.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206564843-1971e974-3522-4ead-90a1-480d0386510e.png)

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [x] The `button` should be on a new line as seen in your chosen Figma design. Kindly fix this 🙏

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206566146-13486f2a-17af-4b32-b1e9-ebb100e8cdc9.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206566064-19b67eda-a9b3-4dc7-bf45-22caa63315d4.png)

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +    height: 846px;
- [ ] Great job 💪. Kindly make sure your `contact me` section is responsive and fills up a desktop viewport width 🙏 

![image](https://user-images.githubusercontent.com/74814780/206567605-38faf182-28bd-432f-a6cd-79662db7f327.png)

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] When on a screen size of `768px` your `images` in the work section disappears. Kindly fix this issue 🙏. They should all display since your desktop design  starts from `768px`

![image](https://user-images.githubusercontent.com/74814780/206568339-1ec5d54e-6313-4a91-a51d-14b2104db285.png)

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +@media (max-width: 768px) {
- [ ] Since this is a mobile-first design it isn't necessary to add a media query of `max-width: 768px` to your design ☺️. Kindly remove the media query of `max-width: 768px` 🙏

2022-12-08 21:23 UTC, Ugboaja-Uchechi commented on style.css
> +    display: none;
- [ ] When on a screen size of `768px` your `images` and `text` in the work section disappears. Kindly fix this issue🙏. They should all display since your desktop design  starts from `768px` ☺️ 

![image](https://user-images.githubusercontent.com/74814780/206569825-5b4c1c0f-f5a4-40b1-8099-7d108668ee7b.png)

2022-12-09 09:55 UTC, zewdu444 commented on style.css
> +    display: none;
I appreciate your thorough comments and have implemented all of your suggestions,  @Ugboaja-Uchechi.

2022-12-09 10:41 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @zewdu444, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/933d15a5d5acd62a4c99c1e2b391cacfbfe61154e349c4af39c9a99d8d10caab/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3236444f6f4477644e474b416736554b492f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 10:58 UTC, merged